[build]
target = "src/webapp/index.html"

dist = "dist"

release = false
# The public URL from which assets are to be served.
public_url = "/"
# Whether to include hash values in the output file names.
filehash = true
# Whether to inject scripts (and module preloads) into the finalized output.
inject_scripts = true
# Run without network access
offline = false

[clean]
# The output dir for all final assets.
dist = "dist"
cargo = true

[tools]
tailwindcss = "3.3.5"

# [[hooks]]
# stage = "pre_build"
# command = "sh"
# command_arguments = ["-c", "tailwindcss -i tailwind.css -o src/webapp/style/main.css --minify"]
