name: build
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**.png"
      - "**cd.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download and install tailwind binary
        run: |
          wget -q https://github.com/tailwindlabs/tailwindcss/releases/download/v3.3.6/tailwindcss-linux-x64 -O tailwindcss
          chmod +x tailwindcss
          mkdir "$HOME/.local/bin"
          mv tailwindcss "$HOME/.local/bin/"
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          targets: wasm32-unknown-unknown
          components: rust-src
      - name: Install webkit2gtk for Tauri
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: "latest"
      - uses: jetli/trunk-action@v0.4.0
        with:
          version: "latest"
      - name: Build
        working-directory: webapp
        run: |
          trunk build --release
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUT_ID }}
          projectName: youtinerary
          directory: dist/
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          workingDirectory: webapp
