name: build

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**.png"
      - "**cd.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Download and install tailwind binary
        run: |
          wget -q https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-arm64 -O tailwindcss
          chmod +x tailwindcss
          echo "$GITHUB_WORKSPACE" >> $GITHUB_PATH

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown
          components: rust-src
      - name: Install webkit2gtk for Tauri
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          # Optional version of wasm-pack to install(eg. '0.9.1', 'latest')
          version: "latest"
      - uses: jetli/trunk-action@v0.4.0
        with:
          # Optional version of trunk to install(eg. 'v0.16.0', 'latest')
          version: "latest"
      - name: Build
        run: |
          trunk build --release
